server:
  port: 8080

spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: plataforma-database-hikari
      auto-commit: false
      connection-timeout: 30000
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/app_database
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  flyway:
    locations: classpath:db/migration,classpath:db/testdata

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: my-client
            client-secret: t0d9kUEVEjeZav5FaM1BtBUycO1iNWYM
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/my-realm
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/my-realm