server:
  port: 8080

#springdoc:
#  api-docs:
#    path: '/api-docs'

swagger-ui:
  path: '/api-docs-ui.html'

spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      pool-name: plataforma-database-hikari
      auto-commit: false
      connection-timeout: 30000
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/imob_database
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  flyway:
    locations: classpath:db/migration,classpath:db/testdata

  swagger-ui:
    oauth:
      clientId: algafood-web
      clientSecret: web123
      use-pkce-with-authorization-code-grant: true
      use-basic-authentication-with-access-code-grant: true

jwt:
  private:
    key: 'classpath:app.key'
  public:
    key: 'classpath:app.pub'

imob:
  storage:
    s3:
      key-id: ${S3_KEY_ID}
      key-secret: ${S3_KEY_SECRET}
      bucket: 'imob.bucket'
      region: 'us-east-1'
    image:
      download-url: 'https://imob.bucket.s3.amazonaws.com'
    document:
      download-url: 'http://localhost:8080/downloads'