CREATE TABLE IF NOT EXISTS TB_ROLE (
   ID                   BIGSERIAL            NOT NULL,
   ROLE                 VARCHAR(50)          NOT NULL,
   DESCRIPTION          VARCHAR(100)         NOT NULL,
   CREATED_AT           TIMESTAMP            NOT NULL DEFAULT CURRENT_TIMESTAMP,
   UPDATED_AT           TIMESTAMP            NULL,
   CONSTRAINT PK_ROLE PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_ROLE_NAME ON TB_ROLE (ROLE);

INSERT INTO TB_ROLE (ROLE, DESCRIPTION) VALUES ('ADMIN', 'Admin') ON CONFLICT (ROLE) DO NOTHING;
INSERT INTO TB_ROLE (ROLE, DESCRIPTION) VALUES ('USER', 'User') ON CONFLICT (ROLE) DO NOTHING;