CREATE TABLE IF NOT EXISTS IMOB_ROLE (
   ID               UUID                 NOT NULL DEFAULT Uuid_generate_v4(),
   NAME             VARCHAR(50)          NOT NULL,
   DESCRIPTION      VARCHAR(100)         NOT NULL,
   CREATED_AT       TIMESTAMP            NOT NULL DEFAULT CURRENT_TIMESTAMP,
   UPDATED_AT       TIMESTAMP            NULL,
   CONSTRAINT PK_IMOB_ROLE PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_ROLE_NAME ON IMOB_ROLE (NAME);