CREATE TABLE IF NOT EXISTS IMOB_GROUP (
    ID          UUID            NOT NULL DEFAULT Uuid_generate_v4(),
    NAME        VARCHAR(60)     NOT NULL,
   CONSTRAINT PK_IMOB_GROUP PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_GROUP_NAME ON IMOB_GROUP (NAME);

CREATE TABLE IMOB_GROUP_ROLE (
    ID         UUID NOT NULL DEFAULT Uuid_generate_v4(),
	GROUP_ID   UUID NOT NULL,
	ROLE_ID    UUID NOT NULL,
	CONSTRAINT PK_IMOB_GROUP_ROLE PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_IMOB_GROUP_ROLE ON IMOB_GROUP_ROLE (GROUP_ID, ROLE_ID);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM PG_CONSTRAINT WHERE CONNAME = 'FK_IMOB_GROUP_ROLE_01') THEN
        ALTER TABLE IMOB_GROUP_ROLE ADD CONSTRAINT FK_IMOB_GROUP_ROLE_01 FOREIGN KEY (GROUP_ID)
        REFERENCES IMOB_GROUP (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
    END IF;
END; $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM PG_CONSTRAINT WHERE CONNAME = 'FK_IMOB_GROUP_ROLE_02') THEN
        ALTER TABLE IMOB_GROUP_ROLE ADD CONSTRAINT FK_IMOB_GROUP_ROLE_02 FOREIGN KEY (ROLE_ID)
        REFERENCES IMOB_ROLE (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
    END IF;
END; $$;