CREATE TABLE IF NOT EXISTS IMOB_USER (
   ID                   UUID            NOT NULL DEFAULT Uuid_generate_v4(),
   NAME                 VARCHAR(70)     NOT NULL,
   EMAIL                VARCHAR(254)    NOT NULL,
   PASSWORD             VARCHAR(60)     NOT NULL,
   ACTIVE               BOOL            NOT NULL,
   BLOCKED              BOOL            NOT NULL,
   CPF                  VARCHAR(14)     NULL,
   TELEPHONE            VARCHAR(20)     NOT NULL,
   PARTNER_ID           UUID            NULL,
   CREATED_AT           TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
   UPDATED_AT           TIMESTAMP       NULL,
   CONSTRAINT PK_IMOB_USER PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_USER_EMAIL ON IMOB_USER (EMAIL);

CREATE UNIQUE INDEX IF NOT EXISTS UK_USER_CPF ON IMOB_USER (CPF)
WHERE CPF IS NOT NULL AND COALESCE(TRIM(CPF),'') <> '';

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM PG_CONSTRAINT WHERE CONNAME = 'FK_USER_PARTNER') THEN
        ALTER TABLE IMOB_USER ADD CONSTRAINT FK_USER_PARTNER FOREIGN KEY (PARTNER_ID)
        REFERENCES IMOB_PARTNER (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
    END IF;
END; $$;

CREATE TABLE IF NOT EXISTS IMOB_USER_GROUP (
   ID                   UUID            NOT NULL DEFAULT Uuid_generate_v4(),
   USER_ID              UUID            NOT NULL,
   GROUP_ID             UUID            NOT NULL,
   CONSTRAINT PK_IMOB_USER_GROUP PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_USER_GROUP ON IMOB_USER_GROUP (USER_ID, GROUP_ID);

DO
$$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM PG_CONSTRAINT WHERE CONNAME = 'FK_IMOB_USER_GROUP_01') THEN
            ALTER TABLE IMOB_USER_GROUP ADD CONSTRAINT FK_IMOB_USER_GROUP_01 FOREIGN KEY (USER_ID)
            REFERENCES IMOB_USER (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
        END IF;
    END;
$$;

DO
$$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM PG_CONSTRAINT WHERE CONNAME = 'FK_IMOB_USER_GROUP_02') THEN
            ALTER TABLE IMOB_USER_GROUP ADD CONSTRAINT FK_IMOB_USER_GROUP_02 FOREIGN KEY (GROUP_ID)
            REFERENCES IMOB_GROUP (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
        END IF;
    END;
$$;