CREATE TABLE IF NOT EXISTS IMOB_PROPERTY_MEDIA (
    ID              UUID    NOT NULL DEFAULT Uuid_generate_v4(),
    PROPERTY_ID     UUID    NOT NULL,
    MEDIA_ID        UUID    NOT NULL,
    CONSTRAINT PK_IMOB_PROPERTY_MEDIA PRIMARY KEY (ID)
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM PG_CONSTRAINT WHERE CONNAME = 'IMOB_PROPERTY_MEDIA_01') THEN
        ALTER TABLE IMOB_PROPERTY_MEDIA ADD CONSTRAINT IMOB_PROPERTY_MEDIA_01 FOREIGN KEY (PROPERTY_ID)
        REFERENCES IMOB_PROPERTY (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
    END IF;
END; $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM PG_CONSTRAINT WHERE CONNAME = 'IMOB_PROPERTY_MEDIA_02') THEN
        ALTER TABLE IMOB_PROPERTY_MEDIA ADD CONSTRAINT IMOB_PROPERTY_MEDIA_02 FOREIGN KEY (MEDIA_ID)
        REFERENCES IMOB_MEDIA (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
    END IF;
END; $$;