CREATE TABLE IF NOT EXISTS IMOB_PROPERTY_AREA_LOCATION (
    ID              UUID    NOT NULL DEFAULT Uuid_generate_v4(),
    PROPERTY_ID     UUID    NOT NULL,
    LOCATION_ID     UUID    NOT NULL,
    CONSTRAINT PK_IMOB_PROPERTY_AREA_LOCATION PRIMARY KEY (ID)
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM PG_CONSTRAINT WHERE CONNAME = 'FK_IMOB_PROPERTY_AREA_LOCATION_01') THEN
        ALTER TABLE IMOB_PROPERTY_AREA_LOCATION ADD CONSTRAINT FK_IMOB_PROPERTY_AREA_LOCATION_01 FOREIGN KEY (PROPERTY_ID)
        REFERENCES IMOB_PROPERTY (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
    END IF;
END; $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM PG_CONSTRAINT WHERE CONNAME = 'FK_IMOB_PROPERTY_AREA_LOCATION_02') THEN
        ALTER TABLE IMOB_PROPERTY_AREA_LOCATION ADD CONSTRAINT FK_IMOB_PROPERTY_AREA_LOCATION_02 FOREIGN KEY (LOCATION_ID)
        REFERENCES IMOB_LOCATION (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
    END IF;
END; $$;