CREATE TABLE IF NOT EXISTS IMOB_RESET_PASSWORD (
    ID              UUID            NOT NULL DEFAULT Uuid_generate_v4(),
    TOKEN           VARCHAR(200)    NOT NULL,
    USER_ID         UUID            NOT NULL,
    EXPIRY_DATE     TIMESTAMP       NOT NULL,
    CONSTRAINT PK_IMOB_RESET_PASSWORD PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UK_RESET_PASSWORD_TOKEN ON IMOB_RESET_PASSWORD (TOKEN);

DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
        WHERE CONSTRAINT_NAME = 'FK_RESET_PASSWORD_USER' AND TABLE_SCHEMA = CURRENT_SCHEMA()) THEN
            ALTER TABLE IMOB_RESET_PASSWORD ADD CONSTRAINT FK_RESET_PASSWORD_USER FOREIGN KEY (USER_ID)
            REFERENCES IMOB_USER (ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
    END IF;
END; $$;