INSERT INTO IMOB_GROUP (NAME) VALUES ('Administrativo') ON CONFLICT (NAME) DO NOTHING;

INSERT INTO IMOB_ROLE (NAME, DESCRIPTION) VALUES ('ADMIN', 'Administrador sistema') ON CONFLICT (NAME) DO NOTHING;
INSERT INTO IMOB_ROLE (NAME, DESCRIPTION) VALUES ('PARTNER', 'Administrador Parceiro') ON CONFLICT (NAME) DO NOTHING;
INSERT INTO IMOB_ROLE (NAME, DESCRIPTION) VALUES ('BROKER', 'Corretor') ON CONFLICT (NAME) DO NOTHING;