INSERT INTO IMOB_USER(NAME, EMAIL, PASSWORD, ACTIVE, BLOCKED, CPF, TELEPHONE, PARTNER_ID)
	VALUES ('Imob Admin', 'dev@imob.com.br', '$2a$10$dOYiLdrWCBpRu/hAKmNcaOLvfD5J16Djh5EnDyyASgU0uvJPMnrSi', TRUE, FALSE, NULL, '62 34147645', NULL)
	ON CONFLICT (EMAIL) DO NOTHING;

INSERT INTO IMOB_GROUP_ROLE(GROUP_ID, ROLE_ID)
WITH
  GROUP_ADMIN AS (SELECT ID FROM IMOB_GROUP WHERE NAME = 'Administrativo'),
  ROLE AS (SELECT ID FROM IMOB_ROLE WHERE NAME = 'ADMIN')
  SELECT GROUP_ADMIN.ID, ROLE.ID FROM GROUP_ADMIN, ROLE
ON CONFLICT (GROUP_ID, ROLE_ID) DO NOTHING;

INSERT INTO IMOB_USER_GROUP(USER_ID, GROUP_ID)
WITH
  USER_ADMIN AS (SELECT ID FROM IMOB_USER WHERE EMAIL = 'dev@imob.com.br'),
  USER_GROUP AS (SELECT ID FROM IMOB_GROUP WHERE NAME = 'Administrativo')
  SELECT USER_ADMIN.ID, USER_GROUP.ID FROM USER_ADMIN, USER_GROUP
ON CONFLICT (USER_ID, GROUP_ID) DO NOTHING;